### ISSUE TITLE
tangata changes the indentation of existing yml files

### ISSUE THREAD

**Issue by b-per** [ciejer/tangata_local#39]
After modifying a model that was already part of a `yml` file, tangata correctly added the new piece of configuration, but also changed the entire indentation of my file in the process.

The new configuration file still works after `dbt test` but the issue is that every single line of the `yml` is now showing up as a change in the git commit.

**Comment by ciejer** [comment]
I have come across this also - seems because the dbt community is manually writing `.yml` rather than autogenerating we've been [writing it "wrong"](https://yaml.org/) with extra indents.

It is suboptimal however to surface changes of this scale when the code is still parseable, and even more suboptimal that YAML comments are being overwritten - so I'll try find an in-place editor (yawn-yaml does this in nodeJS, haven't found a good python one yet)

**Comment by b-per** [comment]
It seems that `ruamel.yaml` allows to keep comments and formatting (some info [here](https://stackoverflow.com/questions/20805418/pyyaml-dump-format/36760452#36760452), but a bit outdated). And being originally a fork from `pyyaml` the move from one to the other might not be too complicated.

**Comment by ciejer** [comment]
I tried `ruamel.yaml` early on and it defaulted to inline yaml (`models: {name: test, description: test description}`. As this is my first python project of anywhere near this scale, I gave up and went for the more popular PyYaml.  
Now I've spent some more time with it and it works - will be in version released shortly.
